# Generated by Django 3.1.1 on 2020-09-28 22:05

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('iquensans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='+ 91 9602723097', max_length=31),
        ),
    ]
