# Generated by Django 3.1.1 on 2020-09-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iquensans', '0003_auto_20200928_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
