# Generated by Django 3.1 on 2020-10-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iquensans', '0008_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(help_text="what's on your mind?"),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
