/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-02-21 07:50:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

public String displayDate() {
		SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd hh:mm");
		Date date = Calendar.getInstance().getTime();
		return dateFormat.format(date);
	}
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>H+ Sport</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header id=\"home\" class=\"header\">\r\n");
      out.write("\t\t<nav class=\"nav\" role=\"navigation\">\r\n");
      out.write("\t\t\t<div class=\"container nav-elements\">\r\n");
      out.write("\t\t\t\t<div class=\"branding\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#home\"><img src=\"images/hpluslogo.svg\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Logo - H Plus Sports\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- branding -->\r\n");
      out.write("\t\t\t\t<ul class=\"navbar\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"register\">Register</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"redirect\">linkedIn</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- navbar -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- container nav-elements -->\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<!-- <div class=\"container tagline\">\r\n");
      out.write("    <h1 class=\"headline\">Our Mission</h1>\r\n");
      out.write("    <p>We support and encourage <em>active and healthy</em> lifestyles, by offering <em>ethically sourced</em> and <em>eco-friendly</em> nutritional products for the <em>performance-driven</em> athlete.</p>\r\n");
      out.write("  </div>container tagline -->\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- #home -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<!-- displays date and time for today -->\r\n");
      out.write("\t\t");
      out.print(displayDate());
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<section id=\"login\" class=\"section\">\r\n");
      out.write("\t\t<div class=\"container tagline\">\r\n");
      out.write("\t\t\t");

				if (request.getAttribute("error") != null) {
			
      out.write("\r\n");
      out.write("\t\t\t");
      out.print(request.getAttribute("error"));
      out.write("<br />\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t<em>LOGIN USER</em>\r\n");
      out.write("\t\t\t<form action=\"login\" method=\"post\">\r\n");
      out.write("\t\t\t\t<label>Email</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"username\" id=\"username\" placeholder=\"username is your email\"><br />\r\n");
      out.write("\t\t\t\t<label>Password</label>\r\n");
      out.write("\t\t\t\t<input type=\"number\" name=\"password\" id=\"password\" placeholder=\"password is  your number\"><br />\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Login\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- #products -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<nav class=\"nav\" role=\"navigation\">\r\n");
      out.write("\t\t\t\t<div class=\"container nav-elements\">\r\n");
      out.write("\t\t\t\t\t<div class=\"branding\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#home\"><img src=\"images/hpluslogo.svg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"Logo - H Plus Sports\"></a>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"address\">\r\n");
      out.write("\t\t\t\t\t\t\t100 Main Street<br> Seattle, WA 98144\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<p class=\"legal\">H+ Sport is a fictitious brand created by\r\n");
      out.write("\t\t\t\tlynda.com solely for the purpose of training. All products and\r\n");
      out.write("\t\t\t\tpeople associated with H+ Sport are also fictitious. Any resemblance\r\n");
      out.write("\t\t\t\tto real brands, products, or people is purely coincidental.\r\n");
      out.write("\t\t\t\tInformation provided about the product is also fictitious and should\r\n");
      out.write("\t\t\t\tnot be construed to be representative of actual products on the\r\n");
      out.write("\t\t\t\tmarket in a similar product category.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- container -->\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
